export const GetFetch = async (url: string, token: string) => {
  try {
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(`Error en la petici贸n: ${response.status}`);
    }

    const data = await response.json();
    return data;
  } catch (error) {
    console.error('Error al hacer la petici贸n GET:', error);
    throw error;
  }
};
export const PatchFetch = async (url: string, token: string, body: object) => {
  try {
    const response = await fetch(url, {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.message || `Error en la petici贸n: ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('Error al hacer la petici贸n PATCH:', error);
    throw error;
  }
};
